namespace IDeepCloneable.Generator;

/// <summary>
/// Options for the Cloneable source generator.
/// </summary>
public class CloneableGeneratorOptions : ICloneableGeneratorOptions
{
    public string AttributeMetadataName => "DeepCloneableAttribute";

    public string GeneratedHeaderComment =>
        $"This file was generated by the IDeepCloneable source generator. (Ver. {ThisAssembly.AssemblyFileVersion})";

    public string ImplementedInterfaceName => "global::IDeepCloneable";

    public string ImplementsMethodName => "DeepClone";

    public string ExtensionsExportFileName => "DeepCloneableExtensions.g.cs";

    public string ExtensionsNamespace => "IDeepCloneable.Generator";

    public string ExtensionsClassName => "DeepCloneableExtensions";
}
