using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace IDeepCloneable.Generator;

public partial class CloneableGenerator
{
    /// <summary>
    /// Generates source code for deep cloning.
    /// </summary>
    private static void Execute(EquatableArray<ClassInfo> classInfos, SourceProductionContext context)
    {
        if (classInfos.Count == 0)
            return;

        // Generate DeepCloneExtensions.g.cs
        var extensionsCode = GenerateDeepCloneExtensions(classInfos);
        context.AddSource("DeepCloneExtensions.g.cs", extensionsCode);

        // Generate partial class implementations for each type that needs DeepClone method
        foreach (var classInfo in classInfos.Where(c => c.NeedsDeepCloneMethod))
        {
            var partialClassCode = GeneratePartialClass(classInfo);
            var fileName = $"{classInfo.ClassName}.DeepClone.g.cs";
            context.AddSource(fileName, partialClassCode);
        }
    }

    private static string GenerateFileHeader()
    {
        return @"// <auto-generated>
// This file was generated by the IDeepCloneable source generator.
// </auto-generated>
#nullable disable
#pragma warning disable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.CompilerServices;
#if NET8_0_OR_GREATER
using System.Runtime.InteropServices;
#endif

";
    }

    private static string GenerateDeepCloneExtensions(EquatableArray<ClassInfo> classInfos)
    {
        var sb = new StringBuilder();
        sb.Append(GenerateFileHeader());
        sb.AppendLine("namespace IDeepCloneable.Generator");
        sb.AppendLine("{");
        sb.AppendLine("    [EditorBrowsable(EditorBrowsableState.Never)]");
        sb.AppendLine("    internal static partial class DeepCloneExtensions");
        sb.AppendLine("    {");

        // Generate CloneInternal methods for each class
        foreach (var classInfo in classInfos)
        {
            var cloneMethod = GenerateCloneInternalMethod(classInfo, classInfos);
            if (!string.IsNullOrEmpty(cloneMethod))
            {
                sb.AppendLine(cloneMethod);
            }
        }

        // Generate special collection clone methods
        var collectionMethods = GenerateCollectionCloneMethods(classInfos);
        sb.AppendLine(collectionMethods);

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string GenerateCloneInternalMethod(ClassInfo classInfo, EquatableArray<ClassInfo> allClassInfos)
    {
        if (classInfo.IsAllImmutable && !classInfo.IsCollection)
        {
            // No need to generate for immutable types
            return string.Empty;
        }

        var sb = new StringBuilder();
        var visibility = classInfo.NeedsDeepCloneMethod ? "internal" : "private";
        var methodName = SanitizeTypeName(classInfo.FullClassName) + "_CloneInternal";

        sb.AppendLine($"        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"        [EditorBrowsable(EditorBrowsableState.Never)]");
        sb.AppendLine($"        {visibility} static {classInfo.FullClassName} {methodName}(this {classInfo.FullClassName} original)");
        sb.AppendLine("        {");

        // Handle null for nullable types
        if (!classInfo.IsValueType)
        {
            sb.AppendLine("            if (original == null) return null;");
        }

        if (classInfo.IsRecord || classInfo.IsValueType)
        {
            // Use 'with' expression for records and structs
            var hasNonImmutableProps = classInfo.Properties.Any(p => p.NeedsDeepClone);
            
            if (hasNonImmutableProps)
            {
                sb.AppendLine("            return original with");
                sb.AppendLine("            {");
                
                bool isFirst = true;
                foreach (var prop in classInfo.Properties)
                {
                    if (prop.NeedsDeepClone)
                    {
                        var cloneCall = GeneratePropertyCloneCall(prop, allClassInfos);
                        sb.AppendLine($"                {prop.Name} = {cloneCall},");
                        isFirst = false;
                    }
                }
                
                sb.AppendLine("            };");
            }
            else
            {
                // All properties are immutable, just return the original
                sb.AppendLine("            return original;");
            }
        }
        else
        {
            // Create new instance for classes
            sb.AppendLine($"            var clone = new {classInfo.FullClassName}();");
            
            foreach (var prop in classInfo.Properties)
            {
                if (prop.IsImmutable)
                {
                    sb.AppendLine($"            clone.{prop.Name} = original.{prop.Name};");
                }
                else
                {
                    var cloneCall = GeneratePropertyCloneCall(prop, allClassInfos);
                    sb.AppendLine($"            clone.{prop.Name} = {cloneCall};");
                }
            }
            
            sb.AppendLine("            return clone;");
        }

        sb.AppendLine("        }");
        sb.AppendLine();

        return sb.ToString();
    }

    private static string GeneratePropertyCloneCall(PropertyInfo prop, EquatableArray<ClassInfo> allClassInfos)
    {
        var propertyAccess = $"original.{prop.Name}";
        
        // Handle nullable
        if (prop.IsNullable)
        {
            var cloneCall = GenerateTypeCloneCall(prop.TypeFullName, propertyAccess, allClassInfos);
            return $"{propertyAccess} == null ? null : {cloneCall}";
        }
        else
        {
            return GenerateTypeCloneCall(prop.TypeFullName, propertyAccess, allClassInfos);
        }
    }

    private static string GenerateTypeCloneCall(string typeFullName, string valueExpression, EquatableArray<ClassInfo> allClassInfos)
    {
        // Check if it's an immutable type first
        if (IsTypeImmutable(typeFullName))
        {
            return valueExpression;
        }

        // Handle List<T>
        if (typeFullName.Contains("System.Collections.Generic.List<"))
        {
            var innerType = ExtractGenericType(typeFullName);
            var methodName = "CloneList_" + SanitizeTypeName(innerType);
            return $"{methodName}({valueExpression})";
        }

        // Handle Dictionary<TKey, TValue>
        if (typeFullName.Contains("System.Collections.Generic.Dictionary<"))
        {
            var methodName = "CloneDictionary_" + SanitizeTypeName(typeFullName);
            return $"{methodName}({valueExpression})";
        }

        // Handle arrays
        if (typeFullName.EndsWith("[]"))
        {
            var elementType = typeFullName.Substring(0, typeFullName.Length - 2);
            var methodName = "CloneArray_" + SanitizeTypeName(elementType);
            return $"{methodName}({valueExpression})";
        }

        // Regular type
        var sanitizedName = SanitizeTypeName(typeFullName);
        return $"{sanitizedName}_CloneInternal({valueExpression})";
    }

    private static string GenerateCollectionCloneMethods(EquatableArray<ClassInfo> classInfos)
    {
        var sb = new StringBuilder();
        var generatedMethods = new HashSet<string>();

        foreach (var classInfo in classInfos)
        {
            foreach (var prop in classInfo.Properties)
            {
                var typeFullName = prop.TypeFullName;

                // Generate List<T> clone method
                if (typeFullName.Contains("System.Collections.Generic.List<"))
                {
                    var innerType = ExtractGenericType(typeFullName);
                    var methodName = "CloneList_" + SanitizeTypeName(innerType);
                    
                    if (!generatedMethods.Contains(methodName))
                    {
                        generatedMethods.Add(methodName);
                        sb.AppendLine(GenerateListCloneMethod(typeFullName, innerType, methodName, classInfos));
                    }
                }

                // Generate Dictionary<TKey, TValue> clone method
                if (typeFullName.Contains("System.Collections.Generic.Dictionary<"))
                {
                    var methodName = "CloneDictionary_" + SanitizeTypeName(typeFullName);
                    
                    if (!generatedMethods.Contains(methodName))
                    {
                        generatedMethods.Add(methodName);
                        sb.AppendLine(GenerateDictionaryCloneMethod(typeFullName, methodName, classInfos));
                    }
                }

                // Generate array clone method
                if (typeFullName.EndsWith("[]"))
                {
                    var elementType = typeFullName.Substring(0, typeFullName.Length - 2);
                    var methodName = "CloneArray_" + SanitizeTypeName(elementType);
                    
                    if (!generatedMethods.Contains(methodName))
                    {
                        generatedMethods.Add(methodName);
                        sb.AppendLine(GenerateArrayCloneMethod(elementType, methodName, classInfos));
                    }
                }
            }
        }

        return sb.ToString();
    }

    private static string GenerateListCloneMethod(string listType, string innerType, string methodName, EquatableArray<ClassInfo> allClassInfos)
    {
        var sb = new StringBuilder();
        var isImmutable = IsTypeImmutable(innerType);

        sb.AppendLine($"        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"        [EditorBrowsable(EditorBrowsableState.Never)]");
        sb.AppendLine($"        private static {listType} {methodName}(this {listType} original)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (original == null) return null;");
        
        if (isImmutable)
        {
            sb.AppendLine($"            return new {listType}(original);");
        }
        else
        {
            sb.AppendLine($"            var list = new {listType}(original.Count);");
            sb.AppendLine("#if NET8_0_OR_GREATER");
            sb.AppendLine("            global::System.Runtime.InteropServices.CollectionMarshal.SetCount(list, original.Count);");
            sb.AppendLine("            for (int i = 0; i < original.Count; i++)");
            sb.AppendLine("            {");
            var cloneCall = GenerateTypeCloneCall(innerType, "original[i]", allClassInfos);
            sb.AppendLine($"                list[i] = {cloneCall};");
            sb.AppendLine("            }");
            sb.AppendLine("#else");
            sb.AppendLine("            foreach (var item in original)");
            sb.AppendLine("            {");
            cloneCall = GenerateTypeCloneCall(innerType, "item", allClassInfos);
            sb.AppendLine($"                list.Add({cloneCall});");
            sb.AppendLine("            }");
            sb.AppendLine("#endif");
            sb.AppendLine("            return list;");
        }
        
        sb.AppendLine("        }");
        sb.AppendLine();

        return sb.ToString();
    }

    private static string GenerateDictionaryCloneMethod(string dictType, string methodName, EquatableArray<ClassInfo> allClassInfos)
    {
        var sb = new StringBuilder();
        
        // Extract key and value types
        var startIndex = dictType.IndexOf('<');
        var endIndex = dictType.LastIndexOf('>');
        if (startIndex < 0 || endIndex <= startIndex)
            return string.Empty;
            
        var typeArgs = dictType.Substring(startIndex + 1, endIndex - startIndex - 1);
        var parts = SplitGenericArgs(typeArgs);
        
        if (parts.Count != 2)
            return string.Empty;
            
        var keyType = parts[0];
        var valueType = parts[1];
        
        var keyIsImmutable = IsTypeImmutable(keyType);
        var valueIsImmutable = IsTypeImmutable(valueType);

        sb.AppendLine($"        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"        [EditorBrowsable(EditorBrowsableState.Never)]");
        sb.AppendLine($"        private static {dictType} {methodName}(this {dictType} original)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (original == null) return null;");
        
        if (keyIsImmutable && valueIsImmutable)
        {
            sb.AppendLine($"            return new {dictType}(original);");
        }
        else
        {
            sb.AppendLine($"            var dict = new {dictType}(original.Count);");
            sb.AppendLine("            foreach (var kvp in original)");
            sb.AppendLine("            {");
            
            var keyClone = keyIsImmutable ? "kvp.Key" : GenerateTypeCloneCall(keyType, "kvp.Key", allClassInfos);
            var valueClone = valueIsImmutable ? "kvp.Value" : GenerateTypeCloneCall(valueType, "kvp.Value", allClassInfos);
            
            sb.AppendLine($"                dict.Add({keyClone}, {valueClone});");
            sb.AppendLine("            }");
            sb.AppendLine("            return dict;");
        }
        
        sb.AppendLine("        }");
        sb.AppendLine();

        return sb.ToString();
    }

    private static List<string> SplitGenericArgs(string args)
    {
        var result = new List<string>();
        var depth = 0;
        var current = new StringBuilder();
        
        foreach (var c in args)
        {
            if (c == '<')
            {
                depth++;
                current.Append(c);
            }
            else if (c == '>')
            {
                depth--;
                current.Append(c);
            }
            else if (c == ',' && depth == 0)
            {
                result.Add(current.ToString().Trim());
                current.Clear();
            }
            else
            {
                current.Append(c);
            }
        }
        
        if (current.Length > 0)
        {
            result.Add(current.ToString().Trim());
        }
        
        return result;
    }

    private static string GenerateArrayCloneMethod(string elementType, string methodName, EquatableArray<ClassInfo> allClassInfos)
    {
        var sb = new StringBuilder();
        var isImmutable = IsTypeImmutable(elementType);
        var arrayType = $"{elementType}[]";

        sb.AppendLine($"        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"        [EditorBrowsable(EditorBrowsableState.Never)]");
        sb.AppendLine($"        private static {arrayType} {methodName}(this {arrayType} original)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (original == null) return null;");
        
        if (isImmutable)
        {
            sb.AppendLine("            return (global::System.Array.Clone(original) as " + arrayType + ");");
        }
        else
        {
            sb.AppendLine($"            var array = new {elementType}[original.Length];");
            sb.AppendLine("            for (int i = 0; i < original.Length; i++)");
            sb.AppendLine("            {");
            var cloneCall = GenerateTypeCloneCall(elementType, "original[i]", allClassInfos);
            sb.AppendLine($"                array[i] = {cloneCall};");
            sb.AppendLine("            }");
            sb.AppendLine("            return array;");
        }
        
        sb.AppendLine("        }");
        sb.AppendLine();

        return sb.ToString();
    }

    private static string GeneratePartialClass(ClassInfo classInfo)
    {
        var sb = new StringBuilder();
        sb.Append(GenerateFileHeader());

        if (!string.IsNullOrEmpty(classInfo.Namespace))
        {
            sb.AppendLine($"namespace {classInfo.Namespace}");
            sb.AppendLine("{");
        }

        var typeKeyword = classInfo.IsRecord ? "record" : (classInfo.IsValueType ? "struct" : "class");
        sb.AppendLine($"    partial {typeKeyword} {classInfo.ClassName} : global::IDeepCloneable<{classInfo.FullClassName}>");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <inheritdoc />");
        sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");

        // Determine method modifiers
        var modifiers = "public";
        if (!classInfo.IsSealed && !classInfo.IsValueType)
        {
            if (classInfo.BaseHasDeepClone)
                modifiers += " override";
            else
                modifiers += " virtual";
        }

        var sanitizedName = SanitizeTypeName(classInfo.FullClassName);
        sb.AppendLine($"        {modifiers} {classInfo.FullClassName} DeepClone() => global::IDeepCloneable.Generator.DeepCloneExtensions.{sanitizedName}_CloneInternal(this);");
        sb.AppendLine("    }");

        if (!string.IsNullOrEmpty(classInfo.Namespace))
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static string ExtractGenericType(string fullTypeName)
    {
        var startIndex = fullTypeName.IndexOf('<');
        var endIndex = fullTypeName.LastIndexOf('>');
        if (startIndex >= 0 && endIndex > startIndex)
        {
            return fullTypeName.Substring(startIndex + 1, endIndex - startIndex - 1);
        }
        return fullTypeName;
    }

    private static string SanitizeTypeName(string typeName)
    {
        // Remove global:: prefix and sanitize for method names
        return typeName
            .Replace("global::", "")
            .Replace("::", "_")
            .Replace(".", "_")
            .Replace("<", "_")
            .Replace(">", "_")
            .Replace(",", "_")
            .Replace(" ", "")
            .Replace("[]", "_Array")
            .Replace("?", "");
    }

    private static bool IsTypeImmutable(string typeFullName)
    {
        // Remove global:: prefix for matching
        var normalizedType = typeFullName.Replace("global::", "");
        
        // Common immutable types
        return normalizedType.Contains("System.String") ||
               normalizedType.Contains("System.Int32") ||
               normalizedType.Contains("System.Int64") ||
               normalizedType.Contains("System.Int16") ||
               normalizedType.Contains("System.UInt32") ||
               normalizedType.Contains("System.UInt64") ||
               normalizedType.Contains("System.UInt16") ||
               normalizedType.Contains("System.Byte") ||
               normalizedType.Contains("System.SByte") ||
               normalizedType.Contains("System.Boolean") ||
               normalizedType.Contains("System.Double") ||
               normalizedType.Contains("System.Single") ||
               normalizedType.Contains("System.Decimal") ||
               normalizedType.Contains("System.Char") ||
               normalizedType.Contains("System.DateTime") ||
               normalizedType.Contains("System.DateTimeOffset") ||
               normalizedType.Contains("System.TimeSpan") ||
               normalizedType.Contains("System.Guid");
    }
}
