namespace IDeepCloneable.Generator;

/// <summary>
/// Options for the Cloneable source generator.
/// </summary>
internal class CloneableGeneratorOptions : CloneableGeneratorOptionsCore
{
    public override string AttributeMetadataName => "DeepCloneableAttribute";

    public override string GeneratedHeaderComment =>
        $"This file was generated by the IDeepCloneable source generator. (Ver. {ThisAssembly.AssemblyFileVersion})";

    public override string ImplementedInterfaceName => "global::IDeepCloneable";

    public override string ExtensionsNamespace => "IDeepCloneable.Generator";

    public override string ExtensionsClassName => "DeepCloneableExtensions";
}
