using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.CodeAnalysis;

namespace IDeepCloneable.Generator;

/// <summary>
/// Generates source code for deep cloning functionality.
/// </summary>
internal static class CodeGenerator
{
    private static readonly List<SpecialTypeInfo> SpecialTypeInfos = new()
    {
        new ListTypeInfo(),
        new DictionaryTypeInfo(),
    };

    /// <summary>
    /// Generates source code for deep cloning.
    ///
    /// NOTICE - Code Generation Rules:
    /// * All generated and referenced type names use fully qualified names starting with global:: to avoid name collisions.
    /// * Code generation uses IndentedStringBuilder for proper indentation.
    /// * Generated file headers follow a common format (see GenerateFileHeader).
    /// </summary>
    public static void Execute(
        EquatableArray<ClassInfo> classInfos,
        SourceProductionContext context
    )
    {
        if (classInfos.Count == 0)
            return;

        // Generate DeepCloneExtensions.g.cs
        var extensionsCode = GenerateDeepCloneExtensions(classInfos);
        context.AddSource("DeepCloneExtensions.g.cs", extensionsCode);

        // Generate partial class implementations for each type that needs DeepClone method
        // Skip types that already have DeepClone method defined (manual or from other generators)
        // Use full class name to avoid collisions when classes have the same simple name in different namespaces
        var generatedFiles = new HashSet<string>();
        foreach (
            var classInfo in classInfos.Where(c => c.NeedsDeepCloneMethod && !c.AlreadyHasDeepClone)
        )
        {
            var partialClassCode = GeneratePartialClass(classInfo);
            // Use sanitized full class name to ensure uniqueness
            var fileName =
                $"{CodeGenerationUtility.SanitizeTypeName(classInfo.FullClassName)}.DeepClone.g.cs";

            // Additional safety check to avoid duplicate file names
            if (!generatedFiles.Contains(fileName))
            {
                generatedFiles.Add(fileName);
                context.AddSource(fileName, partialClassCode);
            }
        }
    }

    private static IndentedStringBuilder GenerateFileHeader(IndentedStringBuilder builder)
    {
        // File header format as specified in the original comments
        var header = $"""
            // <auto-generated>
            // This file was generated by the IDeepCloneable source generator. (Ver. {ThisAssembly.AssemblyFileVersion})
            // </auto-generated>
            #nullable disable
            #pragma warning disable

            using System;
            using System.Collections.Generic;
            """;
        builder.AppendLine(header);
        return builder;
    }

    private static string GenerateDeepCloneExtensions(EquatableArray<ClassInfo> classInfos)
    {
        var builder = new IndentedStringBuilder();
        builder = GenerateFileHeader(builder);
        builder.AppendLine("namespace IDeepCloneable.Generator");
        builder.AppendLine("{");
        builder.AppendLine(
            "    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]"
        );
        builder.AppendLine("    internal static partial class DeepCloneExtensions");
        builder.AppendLine("    {");

        // Generate CloneInternal methods for each class
        // Even if all properties are immutable, we still need to clone reference types (classes)
        // Only skip truly immutable types (value types with immutable fields, strings, etc.)
        // Also skip abstract classes (they can't be instantiated with 'new')
        foreach (var classInfo in classInfos)
        {
            // Skip only if it's a value type AND all properties are immutable
            // Or if it's an abstract class (can't instantiate)
            var skipGeneration = (classInfo.IsValueType && classInfo.IsAllImmutable && !classInfo.IsCollection) 
                               || classInfo.IsAbstract;
            
            if (!skipGeneration)
            {
                builder = GenerateCloneInternalMethod(classInfo, classInfos, builder);
            }
        }

        // Generate special collection clone methods
        builder = GenerateCollectionCloneMethods(classInfos, builder);

        builder.AppendLine("    }");
        builder.AppendLine("}");

        return builder.ToString();
    }

    private static IndentedStringBuilder GenerateCloneInternalMethod(
        ClassInfo classInfo,
        EquatableArray<ClassInfo> allClassInfos,
        IndentedStringBuilder builder
    )
    {
        var visibility = classInfo.NeedsDeepCloneMethod ? "internal" : "private";
        var methodName =
            CodeGenerationUtility.SanitizeTypeName(classInfo.FullClassName) + "_CloneInternal";

        builder.AppendLine("");
        builder.AppendLine(
            $"        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]"
        );
        builder.AppendLine(
            $"        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]"
        );
        builder.AppendLine(
            $"        {visibility} static {classInfo.FullClassName} {methodName}(this {classInfo.FullClassName} original)"
        );
        builder.AppendLine("        {");

        if (!classInfo.IsValueType)
        {
            builder.AppendLine("            if (original == null) return null;");
        }

        if (classInfo.IsRecord || classInfo.IsValueType)
        {
            var hasNonImmutableProps = classInfo.Properties.Any(p => p.NeedsDeepClone);

            if (hasNonImmutableProps)
            {
                builder.AppendLine("            return original with");
                builder.AppendLine("            {");

                foreach (var prop in classInfo.Properties)
                {
                    if (prop.NeedsDeepClone)
                    {
                        var cloneCall = GeneratePropertyCloneCall(prop, allClassInfos);
                        builder.AppendLine($"                {prop.Name} = {cloneCall},");
                    }
                }

                builder.AppendLine("            };");
            }
            else
            {
                builder.AppendLine("            return original;");
            }
        }
        else
        {
            builder.AppendLine($"            var clone = new {classInfo.FullClassName}();");

            foreach (var prop in classInfo.Properties)
            {
                if (prop.IsImmutable)
                {
                    builder.AppendLine($"            clone.{prop.Name} = original.{prop.Name};");
                }
                else
                {
                    var cloneCall = GeneratePropertyCloneCall(prop, allClassInfos);
                    builder.AppendLine($"            clone.{prop.Name} = {cloneCall};");
                }
            }

            builder.AppendLine("            return clone;");
        }

        builder.AppendLine("        }");

        return builder;
    }

    private static string GeneratePropertyCloneCall(
        PropertyInfo prop,
        EquatableArray<ClassInfo> allClassInfos
    )
    {
        var propertyAccess = $"original.{prop.Name}";

        if (prop.IsNullable)
        {
            var cloneCall = GenerateTypeCloneCall(prop.TypeFullName, propertyAccess, allClassInfos);
            return $"{propertyAccess} == null ? null : {cloneCall}";
        }
        else
        {
            return GenerateTypeCloneCall(prop.TypeFullName, propertyAccess, allClassInfos);
        }
    }

    /// <summary>
    /// Generates a clone call for a specific type.
    /// </summary>
    public static string GenerateTypeCloneCall(
        string typeFullName,
        string valueExpression,
        EquatableArray<ClassInfo> allClassInfos
    )
    {
        if (CodeGenerationUtility.IsTypeImmutable(typeFullName))
        {
            return valueExpression;
        }

        // Check special types using SpecialTypeInfo
        foreach (var specialTypeInfo in SpecialTypeInfos)
        {
            if (specialTypeInfo.IsMatch(typeFullName))
            {
                var methodName = specialTypeInfo.GetMethodName(typeFullName);
                return $"{methodName}({valueExpression})";
            }
        }

        // Handle arrays
        if (typeFullName.EndsWith("[]"))
        {
            var elementType = typeFullName.Substring(0, typeFullName.Length - 2);
            var methodName = "CloneArray_" + CodeGenerationUtility.SanitizeTypeName(elementType);
            return $"{methodName}({valueExpression})";
        }

        // Regular type
        var sanitizedName = CodeGenerationUtility.SanitizeTypeName(typeFullName);
        return $"{sanitizedName}_CloneInternal({valueExpression})";
    }

    private static IndentedStringBuilder GenerateCollectionCloneMethods(
        EquatableArray<ClassInfo> classInfos,
        IndentedStringBuilder builder
    )
    {
        var generatedMethods = new HashSet<string>();

        foreach (var classInfo in classInfos)
        {
            foreach (var prop in classInfo.Properties)
            {
                var typeFullName = prop.TypeFullName;

                // Check special types using SpecialTypeInfo
                foreach (var specialTypeInfo in SpecialTypeInfos)
                {
                    if (specialTypeInfo.IsMatch(typeFullName))
                    {
                        var methodName = specialTypeInfo.GetMethodName(typeFullName);

                        if (!generatedMethods.Contains(methodName))
                        {
                            generatedMethods.Add(methodName);
                            builder = specialTypeInfo.GenerateCloneMethod(
                                typeFullName,
                                methodName,
                                classInfos,
                                builder
                            );
                        }
                        break;
                    }
                }

                // Handle arrays
                if (typeFullName.EndsWith("[]"))
                {
                    var elementType = typeFullName.Substring(0, typeFullName.Length - 2);
                    var methodName =
                        "CloneArray_" + CodeGenerationUtility.SanitizeTypeName(elementType);

                    if (!generatedMethods.Contains(methodName))
                    {
                        generatedMethods.Add(methodName);
                        builder = GenerateArrayCloneMethod(
                            elementType,
                            methodName,
                            classInfos,
                            builder
                        );
                    }
                }
            }
        }

        return builder;
    }

    private static IndentedStringBuilder GenerateArrayCloneMethod(
        string elementType,
        string methodName,
        EquatableArray<ClassInfo> allClassInfos,
        IndentedStringBuilder builder
    )
    {
        var isImmutable = CodeGenerationUtility.IsTypeImmutable(elementType);
        var arrayType = $"{elementType}[]";

        builder.AppendLine("");
        builder.AppendLine(
            $"        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]"
        );
        builder.AppendLine(
            $"        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]"
        );
        builder.AppendLine(
            $"        private static {arrayType} {methodName}(this {arrayType} original)"
        );
        builder.AppendLine("        {");
        builder.AppendLine("            if (original == null) return null;");

        if (isImmutable)
        {
            builder.AppendLine(
                $"            return (global::System.Array.Clone(original) as {arrayType});"
            );
        }
        else
        {
            builder.AppendLine($"            var array = new {elementType}[original.Length];");
            builder.AppendLine("            for (int i = 0; i < original.Length; i++)");
            builder.AppendLine("            {");
            var cloneCall = GenerateTypeCloneCall(elementType, "original[i]", allClassInfos);
            builder.AppendLine($"                array[i] = {cloneCall};");
            builder.AppendLine("            }");
            builder.AppendLine("            return array;");
        }

        builder.AppendLine("        }");

        return builder;
    }

    private static string GeneratePartialClass(ClassInfo classInfo)
    {
        var builder = new IndentedStringBuilder();
        builder = GenerateFileHeader(builder);

        // Generate namespace if present
        if (!string.IsNullOrEmpty(classInfo.Namespace))
        {
            builder.AppendLine($"namespace {classInfo.Namespace}");
            builder.AppendLine("{");
        }

        var currentIndent = string.IsNullOrEmpty(classInfo.Namespace) ? "" : "    ";

        // Generate containing type declarations for nested classes
        foreach (var containingTypeName in classInfo.ContainingTypeNames)
        {
            builder.AppendLine($"{currentIndent}partial class {containingTypeName}");
            builder.AppendLine($"{currentIndent}{{");
            currentIndent += "    ";
        }

        var typeKeyword = classInfo.IsRecord
            ? (classInfo.IsValueType ? "record struct" : "record")
            : (classInfo.IsValueType ? "struct" : "class");

        builder.AppendLine(
            $"{currentIndent}partial {typeKeyword} {classInfo.ClassName} : global::IDeepCloneable<{classInfo.FullClassName}>"
        );
        builder.AppendLine($"{currentIndent}{{");
        builder.AppendLine($"{currentIndent}    /// <inheritdoc />");
        builder.AppendLine(
            $"{currentIndent}    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]"
        );

        var modifiers = "public";
        if (!classInfo.IsSealed && !classInfo.IsValueType)
        {
            if (classInfo.BaseHasDeepClone)
                modifiers += " override";
            else
                modifiers += " virtual";
        }

        var sanitizedName = CodeGenerationUtility.SanitizeTypeName(classInfo.FullClassName);
        builder.AppendLine(
            $"{currentIndent}    {modifiers} {classInfo.FullClassName} DeepClone() => global::IDeepCloneable.Generator.DeepCloneExtensions.{sanitizedName}_CloneInternal(this);"
        );
        builder.AppendLine($"{currentIndent}}}");

        // Close containing type declarations
        for (int i = 0; i < classInfo.ContainingTypeNames.Count; i++)
        {
            currentIndent = currentIndent.Substring(0, currentIndent.Length - 4);
            builder.AppendLine($"{currentIndent}}}");
        }

        // Close namespace if present
        if (!string.IsNullOrEmpty(classInfo.Namespace))
        {
            builder.AppendLine("}");
        }

        return builder.ToString();
    }
}
