using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.CodeAnalysis;

namespace IDeepCloneable.Generator;

/// <summary>
/// Generates source code for deep cloning functionality.
/// </summary>
internal static class CodeGenerator
{
    private static readonly List<SpecialTypeInfo> SpecialTypeInfos = new()
    {
        new ListTypeInfo(),
        new DictionaryTypeInfo()
    };

    /// <summary>
    /// Generates source code for deep cloning.
    /// 
    /// NOTICE - Code Generation Rules:
    /// * All generated and referenced type names use fully qualified names starting with global:: to avoid name collisions.
    /// * Code generation uses IndentedStringBuilder for proper indentation.
    /// * Generated file headers follow a common format (see GenerateFileHeader).
    /// </summary>
    public static void Execute(EquatableArray<ClassInfo> classInfos, SourceProductionContext context)
    {
        if (classInfos.Count == 0)
            return;

        // Generate DeepCloneExtensions.g.cs
        var extensionsCode = GenerateDeepCloneExtensions(classInfos);
        context.AddSource("DeepCloneExtensions.g.cs", extensionsCode);

        // Generate partial class implementations for each type that needs DeepClone method
        // Use full class name to avoid collisions when classes have the same simple name in different namespaces
        var generatedFiles = new HashSet<string>();
        foreach (var classInfo in classInfos.Where(c => c.NeedsDeepCloneMethod))
        {
            var partialClassCode = GeneratePartialClass(classInfo);
            // Use sanitized full class name to ensure uniqueness
            var fileName = $"{CodeGenerationUtility.SanitizeTypeName(classInfo.FullClassName)}.DeepClone.g.cs";
            
            // Additional safety check to avoid duplicate file names
            if (!generatedFiles.Contains(fileName))
            {
                generatedFiles.Add(fileName);
                context.AddSource(fileName, partialClassCode);
            }
        }
    }

    private static IndentedStringBuilder GenerateFileHeader(IndentedStringBuilder builder)
    {
        // File header format as specified in the original comments
        var header = $"""
            // <auto-generated>
            // This file was generated by the IDeepCloneable source generator.
            // </auto-generated>
            #nullable disable
            #pragma warning disable

            using System;
            using System.Collections.Generic;
            using System.ComponentModel;
            using System.Runtime.CompilerServices;
            #if NET8_0_OR_GREATER
            using System.Runtime.InteropServices;
            #endif
            
            
            """;
        builder.Append(header);
        return builder;
    }

    private static string GenerateDeepCloneExtensions(EquatableArray<ClassInfo> classInfos)
    {
        var builder = new IndentedStringBuilder();
        builder = GenerateFileHeader(builder);
        builder.Append("namespace IDeepCloneable.Generator");
        builder.Append("{");
        builder.Append("    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        builder.Append("    internal static partial class DeepCloneExtensions");
        builder.Append("    {");
        
        // Generate CloneInternal methods for each class
        // Even if all properties are immutable, we still need to clone reference types (classes)
        // Only skip truly immutable types (value types with immutable fields, strings, etc.)
        foreach (var classInfo in classInfos)
        {
            // Skip only if it's a value type AND all properties are immutable
            // Or if it's a collection (handled separately)
            var skipGeneration = classInfo.IsValueType && classInfo.IsAllImmutable && !classInfo.IsCollection;
            
            if (!skipGeneration)
            {
                builder = GenerateCloneInternalMethod(classInfo, classInfos, builder);
            }
        }

        // Generate special collection clone methods
        builder = GenerateCollectionCloneMethods(classInfos, builder);

        builder.Append("    }");
        builder.Append("}");

        return builder.ToString();
    }

    private static IndentedStringBuilder GenerateCloneInternalMethod(ClassInfo classInfo, EquatableArray<ClassInfo> allClassInfos, IndentedStringBuilder builder)
    {
        var visibility = classInfo.NeedsDeepCloneMethod ? "internal" : "private";
        var methodName = CodeGenerationUtility.SanitizeTypeName(classInfo.FullClassName) + "_CloneInternal";

        builder.Append("");
        builder.Append($"        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
        builder.Append($"        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        builder.Append($"        {visibility} static {classInfo.FullClassName} {methodName}(this {classInfo.FullClassName} original)");
        builder.Append("        {");

        if (!classInfo.IsValueType)
        {
            builder.Append("            if (original == null) return null;");
        }

        if (classInfo.IsRecord || classInfo.IsValueType)
        {
            var hasNonImmutableProps = classInfo.Properties.Any(p => p.NeedsDeepClone);
            
            if (hasNonImmutableProps)
            {
                builder.Append("            return original with");
                builder.Append("            {");
                
                foreach (var prop in classInfo.Properties)
                {
                    if (prop.NeedsDeepClone)
                    {
                        var cloneCall = GeneratePropertyCloneCall(prop, allClassInfos);
                        builder.Append($"                {prop.Name} = {cloneCall},");
                    }
                }
                
                builder.Append("            };");
            }
            else
            {
                builder.Append("            return original;");
            }
        }
        else
        {
            builder.Append($"            var clone = new {classInfo.FullClassName}();");
            
            foreach (var prop in classInfo.Properties)
            {
                if (prop.IsImmutable)
                {
                    builder.Append($"            clone.{prop.Name} = original.{prop.Name};");
                }
                else
                {
                    var cloneCall = GeneratePropertyCloneCall(prop, allClassInfos);
                    builder.Append($"            clone.{prop.Name} = {cloneCall};");
                }
            }
            
            builder.Append("            return clone;");
        }

        builder.Append("        }");
        
        return builder;
    }

    private static string GeneratePropertyCloneCall(PropertyInfo prop, EquatableArray<ClassInfo> allClassInfos)
    {
        var propertyAccess = $"original.{prop.Name}";
        
        if (prop.IsNullable)
        {
            var cloneCall = GenerateTypeCloneCall(prop.TypeFullName, propertyAccess, allClassInfos);
            return $"{propertyAccess} == null ? null : {cloneCall}";
        }
        else
        {
            return GenerateTypeCloneCall(prop.TypeFullName, propertyAccess, allClassInfos);
        }
    }

    /// <summary>
    /// Generates a clone call for a specific type.
    /// </summary>
    public static string GenerateTypeCloneCall(string typeFullName, string valueExpression, EquatableArray<ClassInfo> allClassInfos)
    {
        if (CodeGenerationUtility.IsTypeImmutable(typeFullName))
        {
            return valueExpression;
        }

        // Check special types using SpecialTypeInfo
        foreach (var specialTypeInfo in SpecialTypeInfos)
        {
            if (specialTypeInfo.IsMatch(typeFullName))
            {
                var methodName = specialTypeInfo.GetMethodName(typeFullName);
                return $"{methodName}({valueExpression})";
            }
        }

        // Handle arrays
        if (typeFullName.EndsWith("[]"))
        {
            var elementType = typeFullName.Substring(0, typeFullName.Length - 2);
            var methodName = "CloneArray_" + CodeGenerationUtility.SanitizeTypeName(elementType);
            return $"{methodName}({valueExpression})";
        }

        // Regular type
        var sanitizedName = CodeGenerationUtility.SanitizeTypeName(typeFullName);
        return $"{sanitizedName}_CloneInternal({valueExpression})";
    }

    private static IndentedStringBuilder GenerateCollectionCloneMethods(EquatableArray<ClassInfo> classInfos, IndentedStringBuilder builder)
    {
        var generatedMethods = new HashSet<string>();

        foreach (var classInfo in classInfos)
        {
            foreach (var prop in classInfo.Properties)
            {
                var typeFullName = prop.TypeFullName;

                // Check special types using SpecialTypeInfo
                foreach (var specialTypeInfo in SpecialTypeInfos)
                {
                    if (specialTypeInfo.IsMatch(typeFullName))
                    {
                        var methodName = specialTypeInfo.GetMethodName(typeFullName);
                        
                        if (!generatedMethods.Contains(methodName))
                        {
                            generatedMethods.Add(methodName);
                            builder = specialTypeInfo.GenerateCloneMethod(typeFullName, methodName, classInfos, builder);
                        }
                        break;
                    }
                }

                // Handle arrays
                if (typeFullName.EndsWith("[]"))
                {
                    var elementType = typeFullName.Substring(0, typeFullName.Length - 2);
                    var methodName = "CloneArray_" + CodeGenerationUtility.SanitizeTypeName(elementType);
                    
                    if (!generatedMethods.Contains(methodName))
                    {
                        generatedMethods.Add(methodName);
                        builder = GenerateArrayCloneMethod(elementType, methodName, classInfos, builder);
                    }
                }
            }
        }
        
        return builder;
    }

    private static IndentedStringBuilder GenerateArrayCloneMethod(string elementType, string methodName, EquatableArray<ClassInfo> allClassInfos, IndentedStringBuilder builder)
    {
        var isImmutable = CodeGenerationUtility.IsTypeImmutable(elementType);
        var arrayType = $"{elementType}[]";

        builder.Append("");
        builder.Append($"        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
        builder.Append($"        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        builder.Append($"        private static {arrayType} {methodName}(this {arrayType} original)");
        builder.Append("        {");
        builder.Append("            if (original == null) return null;");
        
        if (isImmutable)
        {
            builder.Append($"            return (global::System.Array.Clone(original) as {arrayType});");
        }
        else
        {
            builder.Append($"            var array = new {elementType}[original.Length];");
            builder.Append("            for (int i = 0; i < original.Length; i++)");
            builder.Append("            {");
            var cloneCall = GenerateTypeCloneCall(elementType, "original[i]", allClassInfos);
            builder.Append($"                array[i] = {cloneCall};");
            builder.Append("            }");
            builder.Append("            return array;");
        }
        
        builder.Append("        }");
        
        return builder;
    }

    private static string GeneratePartialClass(ClassInfo classInfo)
    {
        var builder = new IndentedStringBuilder();
        builder = GenerateFileHeader(builder);

        if (!string.IsNullOrEmpty(classInfo.Namespace))
        {
            builder.Append($"namespace {classInfo.Namespace}");
            builder.Append("{");
        }

        var typeKeyword = classInfo.IsRecord 
            ? (classInfo.IsValueType ? "record struct" : "record")
            : (classInfo.IsValueType ? "struct" : "class");
        var indent = string.IsNullOrEmpty(classInfo.Namespace) ? "" : "    ";
        
        builder.Append($"{indent}partial {typeKeyword} {classInfo.ClassName} : global::IDeepCloneable<{classInfo.FullClassName}>");
        builder.Append($"{indent}{{");
        builder.Append($"{indent}    /// <inheritdoc />");
        builder.Append($"{indent}    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");

        var modifiers = "public";
        if (!classInfo.IsSealed && !classInfo.IsValueType)
        {
            if (classInfo.BaseHasDeepClone)
                modifiers += " override";
            else
                modifiers += " virtual";
        }

        var sanitizedName = CodeGenerationUtility.SanitizeTypeName(classInfo.FullClassName);
        builder.Append($"{indent}    {modifiers} {classInfo.FullClassName} DeepClone() => global::IDeepCloneable.Generator.DeepCloneExtensions.{sanitizedName}_CloneInternal(this);");
        builder.Append($"{indent}}}");

        if (!string.IsNullOrEmpty(classInfo.Namespace))
        {
            builder.Append("}");
        }

        return builder.ToString();
    }
}
