using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.CodeAnalysis;

namespace IDeepCloneable.Generator;

/// <summary>
/// Generates source code for deep cloning functionality.
/// </summary>
internal static class CodeGenerator
{
    private static readonly List<SpecialTypeInfo> SpecialTypeInfos = new()
    {
        new ArrayTypeInfo(),
        new ListTypeInfo(),
        new DictionaryTypeInfo(),
        new HashSetTypeInfo(),
        new SortedSetTypeInfo(),
        new StackTypeInfo(),
        new QueueTypeInfo(),
        new ObservableCollectionTypeInfo(),
        new ReadOnlyCollectionTypeInfo(),
        new ImmutableListTypeInfo(),
        new ImmutableArrayTypeInfo(),
        new ImmutableHashSetTypeInfo(),
        new ImmutableDictionaryTypeInfo(),
    };

    /// <summary>
    /// Generates source code for deep cloning.
    ///
    /// NOTICE - Code Generation Rules:
    /// * All generated and referenced type names use fully qualified names starting with global:: to avoid name collisions.
    /// * Code generation uses IndentedStringBuilder for proper indentation.
    /// * Generated file headers follow a common format (see GenerateFileHeader).
    /// </summary>
    public static void Execute(
        EquatableArray<ClassInfo> classInfos,
        SourceProductionContext context
    )
    {
        if (classInfos.Count == 0)
            return;

        // Generate DeepCloneExtensions.g.cs
        var extensionsCode = GenerateDeepCloneExtensions(classInfos);
        context.AddSource("DeepCloneExtensions.g.cs", extensionsCode);

        // Generate partial class implementations for each type that needs DeepClone method
        // Skip types that already have DeepClone method defined (manual or from other generators)
        // Use full class name to avoid collisions when classes have the same simple name in different namespaces
        var generatedFiles = new HashSet<string>();
        foreach (
            var classInfo in classInfos.Where(c => c.NeedsDeepCloneMethod && !c.AlreadyHasDeepClone)
        )
        {
            var partialClassCode = GeneratePartialClass(classInfo);
            // Use sanitized full class name to ensure uniqueness
            var fileName =
                $"{CodeGenerationUtility.SanitizeTypeName(classInfo.FullClassName)}.DeepClone.g.cs";

            // Additional safety check to avoid duplicate file names
            if (!generatedFiles.Contains(fileName))
            {
                generatedFiles.Add(fileName);
                context.AddSource(fileName, partialClassCode);
            }
        }
    }

    private static IndentedStringBuilder GenerateFileHeader(IndentedStringBuilder builder)
    {
        // File header format as specified in the original comments
        var header = $"""
            // <auto-generated>
            // This file was generated by the IDeepCloneable source generator. (Ver. {ThisAssembly.AssemblyFileVersion})
            // </auto-generated>
            #nullable disable
            #pragma warning disable

            using System;
            using System.Collections.Generic;
            """;
        builder.AppendLine(header);
        return builder;
    }

    private static string GenerateDeepCloneExtensions(EquatableArray<ClassInfo> classInfos)
    {
        var builder = new IndentedStringBuilder();
        builder = GenerateFileHeader(builder);
        builder.AppendLine("namespace IDeepCloneable.Generator");
        builder.AppendLine("{");
        builder.IncreaseIndent();
        builder.AppendLine(
            "[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]"
        );
        builder.AppendLine("internal static partial class DeepCloneExtensions");
        builder.AppendLine("{");
        builder.IncreaseIndent();

        // Generate CloneInternal methods for each class
        // Even if all properties are immutable, we still need to clone reference types (classes)
        // Only skip truly immutable types (value types with immutable fields, strings, etc.)
        // Also skip abstract classes (they can't be instantiated)
        // Also skip types that are handled by special type handlers
        foreach (var classInfo in classInfos)
        {
            // Check if this type is handled by a special type handler
            bool isSpecialType = false;
            foreach (var specialTypeInfo in SpecialTypeInfos)
            {
                if (specialTypeInfo.IsMatch(classInfo.FullClassName))
                {
                    isSpecialType = true;
                    break;
                }
            }
            
            // Skip only if it's a value type AND all properties are immutable
            // Or if it's an abstract class (can't instantiate)
            // Or if it's a special type (handled by special type handlers)
            var skipGeneration = (classInfo.IsValueType && classInfo.IsAllImmutable && !classInfo.IsCollection) 
                               || classInfo.IsAbstract
                               || isSpecialType;
            
            if (!skipGeneration)
            {
                builder = GenerateCloneInternalMethod(classInfo, classInfos, builder);
            }
        }

        // Generate special collection clone methods
        builder = GenerateCollectionCloneMethods(classInfos, builder);

        builder.DecreaseIndent();
        builder.AppendLine("}");
        builder.DecreaseIndent();
        builder.AppendLine("}");

        return builder.ToString();
    }

    /// <summary>
    /// Determines whether to use 'with' syntax for cloning a record or value type.
    /// </summary>
    private static bool ShouldUseWithSyntax(ClassInfo classInfo)
    {
        // Always use 'with' for reference type records to create a new instance
        // For value types, only use 'with' if there are mutable properties
        var hasNonImmutableProps = classInfo.Properties.Any(p => p.NeedsDeepClone);
        return hasNonImmutableProps || (classInfo.IsRecord && !classInfo.IsValueType);
    }

    private static IndentedStringBuilder GenerateCloneInternalMethod(
        ClassInfo classInfo,
        EquatableArray<ClassInfo> allClassInfos,
        IndentedStringBuilder builder
    )
    {
        var visibility = classInfo.NeedsDeepCloneMethod ? "internal" : "private";
        var methodName =
            CodeGenerationUtility.SanitizeTypeName(classInfo.FullClassName) + "_CloneInternal";

        builder.AppendLine("");
        builder.AppendLine($"{CodeTemplateContents.AggressiveInliningAttribute}");
        builder.AppendLine($"{CodeTemplateContents.EditorBrowsableAttribute}");
        builder.AppendLine(
            $"{visibility} static {classInfo.FullClassName} {methodName}(this {classInfo.FullClassName} original)"
        );
        builder.AppendLine("{");
        builder.IncreaseIndent();

        if (!classInfo.IsValueType)
        {
            builder.AppendLine("if (original == null) return null;");
        }

        if (classInfo.IsRecord || classInfo.IsValueType)
        {
            if (ShouldUseWithSyntax(classInfo))
            {
                builder.AppendLine("return original with");
                builder.AppendLine("{");
                builder.IncreaseIndent();

                foreach (var prop in classInfo.Properties)
                {
                    if (prop.NeedsDeepClone)
                    {
                        var cloneCall = GeneratePropertyCloneCall(prop, allClassInfos);
                        builder.AppendLine($"{prop.Name} = {cloneCall},");
                    }
                }

                builder.DecreaseIndent();
                builder.AppendLine("};");
            }
            else
            {
                // Only return original for immutable value types
                builder.AppendLine("return original;");
            }
        }
        else
        {
            builder.AppendLine($"var clone = new {classInfo.FullClassName}();");

            foreach (var prop in classInfo.Properties)
            {
                if (prop.IsImmutable)
                {
                    builder.AppendLine($"clone.{prop.Name} = original.{prop.Name};");
                }
                else
                {
                    var cloneCall = GeneratePropertyCloneCall(prop, allClassInfos);
                    builder.AppendLine($"clone.{prop.Name} = {cloneCall};");
                }
            }

            builder.AppendLine("return clone;");
        }

        builder.DecreaseIndent();
        builder.AppendLine("}");

        return builder;
    }

    private static string GeneratePropertyCloneCall(
        PropertyInfo prop,
        EquatableArray<ClassInfo> allClassInfos
    )
    {
        var propertyAccess = $"original.{prop.Name}";

        if (prop.IsNullable)
        {
            var cloneCall = GenerateTypeCloneCall(prop.TypeFullName, propertyAccess, allClassInfos);
            return $"{propertyAccess} == null ? null : {cloneCall}";
        }
        else
        {
            return GenerateTypeCloneCall(prop.TypeFullName, propertyAccess, allClassInfos);
        }
    }

    /// <summary>
    /// Generates a clone call for a specific type.
    /// </summary>
    public static string GenerateTypeCloneCall(
        string typeFullName,
        string valueExpression,
        EquatableArray<ClassInfo> allClassInfos
    )
    {
        if (CodeGenerationUtility.IsTypeImmutable(typeFullName))
        {
            return valueExpression;
        }

        // Check special types using SpecialTypeInfo (includes arrays)
        foreach (var specialTypeInfo in SpecialTypeInfos)
        {
            if (specialTypeInfo.IsMatch(typeFullName))
            {
                var methodName = specialTypeInfo.GetMethodName(typeFullName);
                return $"{methodName}({valueExpression})";
            }
        }

        // Regular type
        var sanitizedName = CodeGenerationUtility.SanitizeTypeName(typeFullName);
        return $"{sanitizedName}_CloneInternal({valueExpression})";
    }

    private static IndentedStringBuilder GenerateCollectionCloneMethods(
        EquatableArray<ClassInfo> classInfos,
        IndentedStringBuilder builder
    )
    {
        var generatedMethods = new HashSet<string>();
        var typesToProcess = new Queue<string>();

        // First, collect all property types
        foreach (var classInfo in classInfos)
        {
            foreach (var prop in classInfo.Properties)
            {
                typesToProcess.Enqueue(prop.TypeFullName);
            }
        }

        // Process types and their nested types
        while (typesToProcess.Count > 0)
        {
            var typeFullName = typesToProcess.Dequeue();

            // Check special types using SpecialTypeInfo (now includes arrays)
            foreach (var specialTypeInfo in SpecialTypeInfos)
            {
                if (specialTypeInfo.IsMatch(typeFullName))
                {
                    var methodName = specialTypeInfo.GetMethodName(typeFullName);

                    if (!generatedMethods.Contains(methodName))
                    {
                        generatedMethods.Add(methodName);
                        builder = specialTypeInfo.GenerateCloneMethod(
                            typeFullName,
                            methodName,
                            classInfos,
                            builder
                        );
                        
                        // Extract inner type(s) and add to queue for processing
                        var innerType = CodeGenerationUtility.ExtractGenericType(typeFullName);
                        if (innerType != typeFullName && !string.IsNullOrEmpty(innerType))
                        {
                            typesToProcess.Enqueue(innerType);
                        }
                        
                        // For arrays, also extract and queue the element type
                        if (typeFullName.Contains("[") && typeFullName.Contains("]"))
                        {
                            var bracketIndex = typeFullName.IndexOf('[');
                            var elementType = typeFullName.Substring(0, bracketIndex);
                            if (!string.IsNullOrEmpty(elementType))
                            {
                                typesToProcess.Enqueue(elementType);
                            }
                        }
                    }
                    break;
                }
            }
        }

        return builder;
    }

    private static string GeneratePartialClass(ClassInfo classInfo)
    {
        var builder = new IndentedStringBuilder();
        builder = GenerateFileHeader(builder);

        // Generate namespace if present
        if (!string.IsNullOrEmpty(classInfo.Namespace))
        {
            builder.AppendLine($"namespace {classInfo.Namespace}");
            builder.AppendLine("{");
            builder.IncreaseIndent();
        }

        // Generate containing type declarations for nested classes
        foreach (var containingTypeName in classInfo.ContainingTypeNames)
        {
            builder.AppendLine($"partial class {containingTypeName}");
            builder.AppendLine("{");
            builder.IncreaseIndent();
        }

        var typeKeyword = classInfo.IsRecord
            ? (classInfo.IsValueType ? "record struct" : "record")
            : (classInfo.IsValueType ? "struct" : "class");

        builder.AppendLine(
            $"partial {typeKeyword} {classInfo.ClassName} : global::IDeepCloneable<{classInfo.FullClassName}>"
        );
        builder.AppendLine("{");
        builder.IncreaseIndent();
        builder.AppendLine("/// <inheritdoc />");
        
        var modifiers = "public";
        if (!classInfo.IsSealed && !classInfo.IsValueType)
        {
            if (classInfo.IsAbstract)
                modifiers += " abstract";
            else if (classInfo.BaseHasDeepClone)
                modifiers += " override";
            else
                modifiers += " virtual";
        }

        var sanitizedName = CodeGenerationUtility.SanitizeTypeName(classInfo.FullClassName);
        
        if (classInfo.IsAbstract)
        {
            // Abstract classes have abstract DeepClone method without implementation
            builder.AppendLine($"{modifiers} {classInfo.FullClassName} DeepClone();");
        }
        else if (classInfo.IsValueType && classInfo.IsAllImmutable && !classInfo.IsCollection)
        {
            // Immutable value types can just return themselves
            builder.AppendLine($"{CodeTemplateContents.AggressiveInliningAttribute}");
            builder.AppendLine($"{modifiers} {classInfo.FullClassName} DeepClone()");
            builder.AppendLine("    => this;");
        }
        else
        {
            // Concrete classes have MethodImpl attribute and call CloneInternal
            builder.AppendLine($"{CodeTemplateContents.AggressiveInliningAttribute}");
            builder.AppendLine($"{modifiers} {classInfo.FullClassName} DeepClone()");
            builder.AppendLine($"    => global::IDeepCloneable.Generator.DeepCloneExtensions.{sanitizedName}_CloneInternal(this);");
        }
        
        builder.DecreaseIndent();
        builder.AppendLine("}");

        // Close containing type declarations
        for (int i = 0; i < classInfo.ContainingTypeNames.Count; i++)
        {
            builder.DecreaseIndent();
            builder.AppendLine("}");
        }

        // Close namespace if present
        if (!string.IsNullOrEmpty(classInfo.Namespace))
        {
            builder.DecreaseIndent();
            builder.AppendLine("}");
        }

        return builder.ToString();
    }
}
