using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Threading;
using Microsoft.CodeAnalysis;

namespace IDeepCloneable.Generator;

/// <summary>
/// Base class for incremental source generators for automatic DeepClone implementation.
/// </summary>
internal abstract class CloneableGeneratorCore<TOptions>() : IIncrementalGenerator
    where TOptions : CloneableGeneratorOptionsCore, new()
{
    /// <summary>
    /// Generator options instance.
    /// </summary>
    private static readonly TOptions options = new();

    /// <summary>
    /// Type analyzer instance.
    /// </summary>
    private readonly TypeAnalyzer _typeAnalyzer = new(options);

    /// <summary>
    /// Code generator instance.
    /// </summary>
    private readonly CodeGenerator _codeGenerator = new(options);

    /// <summary>
    /// Initializes the incremental generator.
    /// </summary>
    public virtual void Initialize(IncrementalGeneratorInitializationContext context)
    {
        GenerateEmbbedAttributes(context);
        var classDeclarations = context
            .SyntaxProvider.ForAttributeWithMetadataName(
                options.AttributeMetadataName,
                predicate: static (node, _) => true,
                transform: TransformFunc
            )
            .Where(static m => m.HasValue)
            .SelectMany(static (m, _) => m!.Value)
            .Collect();

        context.RegisterSourceOutput(
            classDeclarations,
            (spc, sources) => Execute(DropDuplicates(sources), spc)
        );
    }

    /// <summary>
    /// Transforms the syntax context into class information.
    /// </summary>
    protected virtual EquatableArray<ClassInfo>? TransformFunc(
        GeneratorAttributeSyntaxContext ctx,
        CancellationToken cancellationToken
    ) => _typeAnalyzer.GetRelationalAllClassInfo(ctx);

    /// <summary>
    /// Executes the code generation process.
    /// </summary>
    protected virtual void Execute(
        List<ClassInfo> allClassInfos,
        SourceProductionContext context
    ) => _codeGenerator.Execute(allClassInfos, context);

    /// <summary>
    /// Drops duplicate ClassInfo entries based on FullClassName.
    /// </summary>
    protected List<ClassInfo> DropDuplicates(ImmutableArray<ClassInfo> classInfos)
    {
        var result = new List<ClassInfo>();
        var seenTypes = new HashSet<string>();
        foreach (
            var classInfo in from classInfo in classInfos
            where !seenTypes.Contains(classInfo.FullClassName)
            select classInfo
        )
        {
            seenTypes.Add(classInfo.FullClassName);
            result.Add(classInfo);
        }

        return result;
    }

    /// <summary>
    /// Generates embedded attribute classes if configured to do so.
    /// </summary>
    protected virtual void GenerateEmbbedAttributes(IncrementalGeneratorInitializationContext context)
    {
        if (!options.GenerateAttributes)
        {
            return;
        }

        var builder = new IndentedStringBuilder();
        // add file header comment
        builder.AppendLine(
            $"""
            // <auto-generated>
            // {options.GeneratedHeaderComment}
            // </auto-generated>

            """
        );

        // first, add EmbeddedAttribute
        builder.AppendLine(
            """
            namespace Microsoft.CodeAnalysis
            {
                internal sealed partial class EmbeddedAttribute : global::System.Attribute { }
            }

            """
        );

        if (options.ExportAttributeNamespace != null)
        {
            builder.AppendLine($"namespace {options.ExportAttributeNamespace}");
            builder.AppendLine("{");
            builder.IncreaseIndent();
        }

        // next, add [ShallowCloneAttribute] and [CloneIgnoreAttribute]
        if (!string.IsNullOrEmpty(options.ShallowCloneAttributeName))
        {
            builder.AppendLine(
                $$"""
                /// <summary>
                /// Marks a field or property to be shallow-copied during DeepClone operations.
                /// Properties or fields marked with this attribute will have their references copied directly
                /// without creating a deep clone of the object.
                /// </summary>
                [global::System.AttributeUsage(
                    global::System.AttributeTargets.Property | global::System.AttributeTargets.Field,
                    Inherited = false,
                    AllowMultiple = false
                )]
                internal sealed class {{options.ShallowCloneAttributeName}} : global::System.Attribute { }

                """
            );
        }
        if (!string.IsNullOrEmpty(options.CloneIgnoreAttributeName))
        {
            builder.AppendLine(
                $$"""
                /// <summary>
                /// Marks a field or property to be ignored during DeepClone operations.
                /// Properties or fields marked with this attribute will not be cloned and will retain their default values.
                /// </summary>
                [global::System.AttributeUsage(
                    global::System.AttributeTargets.Property | global::System.AttributeTargets.Field,
                    Inherited = false,
                    AllowMultiple = false
                )]
                internal sealed class {{options.CloneIgnoreAttributeName}} : global::System.Attribute { }

                """
            );
        }

        if (options.ExportAttributeNamespace != null)
        {
            builder.DecreaseIndent();
            builder.AppendLine("}");
        }

        var source = builder.ToString();
        context.RegisterPostInitializationOutput(i =>
        {
            i.AddSource($"{options.AttributeExportFileName}.g.cs", source);
        });
    }
}
