namespace IDeepCloneable.Generator;

/// <summary>
/// Options for the Cloneable source generator.
/// </summary>
internal abstract class CloneableGeneratorOptionsCore
{
    /// <summary>
    /// The name of the source generator.
    /// e.g. "IDeepCloneableGenerator"
    /// </summary>
    public virtual string GeneratorName => "IDeepCloneableGenerator";

    /// <summary>
    /// The metadata name of the attribute that marks types for DeepClone generation.
    /// e.g. "DeepCloneableAttribute"
    /// </summary>
    public abstract string AttributeMetadataName { get; }

    /// <summary>
    /// The name of the interface that the generated DeepClone methods will implement.
    /// If empty, no interface will be implemented.
    /// e.g. "global::IDeepCloneable"
    /// </summary>
    public abstract string ImplementedInterfaceName { get; }

    /// <summary>
    /// The header comment to include in generated files.
    /// </summary>
    public virtual string GeneratedHeaderComment =>
        "This file was generated by the IDeepCloneable source generator.";

    /// <summary>
    /// The name of the file to export the partial classes to.
    /// e.g. "IDeepCloneableGenerator.Classes" (without .g.cs)
    /// </summary>
    public virtual string PartialClassFileName => $"{GeneratorName}.Classes";

    /// <summary>
    /// The name of the file to export the extension methods to.
    /// e.g. "DeepCloneableExtensions" (without .g.cs)
    /// </summary>
    public virtual string ExtensionsExportFileName => $"{GeneratorName}.Extensions";

    /// <summary>
    /// The namespace for the generated extension methods.
    /// e.g. "IDeepCloneable.Generator"
    /// </summary>
    public virtual string ExtensionsNamespace => "IDeepCloneable.Generator";

    /// <summary>
    /// The class name for the generated extension methods.
    /// e.g. "DeepCloneableExtensions"
    /// </summary>
    public virtual string ExtensionsClassName => "DeepCloneableExtensions";

    /// <summary>
    /// The name of the DeepClone method to implement.
    /// e.g. "DeepClone"
    /// </summary>
    public virtual string ImplementsMethodName => "DeepClone";

    /// <summary>
    /// Whether to generate the attribute classes used for marking types and members.
    /// </summary>
    public virtual bool GenerateAttributes => true;

    /// <summary>
    /// The name of the file to export the attribute classes to.
    /// e.g. "IDeepCloneableGenerator.Attributes" (without .g.cs)
    /// </summary>
    public virtual string AttributeExportFileName => $"{GeneratorName}.Attributes";

    /// <summary>
    /// The namespace to use for the generated attribute classes.
    /// If null, export to the global namespace.
    /// </summary>
    public virtual string? ExportAttributeNamespace => null;

    /// <summary>
    /// The metadata name of the attribute that marks properties/fields to be ignored during cloning.
    /// e.g. "CloneIgnoreAttribute"
    /// </summary>
    public virtual string CloneIgnoreAttributeName => "CloneIgnoreAttribute";

    /// <summary>
    /// The metadata name of the attribute that marks properties/fields to be shallow-copied during cloning.
    /// e.g. "ShallowCloneAttribute"
    /// </summary>
    public virtual string ShallowCloneAttributeName => "ShallowCloneAttribute";
}
