namespace IDeepCloneable.Generator;

/// <summary>
/// Options for the Cloneable source generator.
/// </summary>
public abstract class CloneableGeneratorOptionsCore
{
    /// <summary>
    /// The metadata name of the attribute that marks types for DeepClone generation.
    /// e.g. "DeepCloneableAttribute"
    /// </summary>
    public abstract string AttributeMetadataName { get; }

    /// <summary>
    /// The name of the interface that the generated DeepClone methods will implement.
    /// If empty, no interface will be implemented.
    /// e.g. "global::IDeepCloneable"
    /// </summary>
    public abstract string ImplementedInterfaceName { get; }

    /// <summary>
    /// The header comment to include in generated files.
    /// </summary>
    public virtual string GeneratedHeaderComment =>
        "This file was generated by the IDeepCloneable source generator.";

    /// <summary>
    /// The name of the file to export the extension methods to.
    /// e.g. "DeepCloneableExtensions" (without .g.cs)
    /// </summary>
    public virtual string ExtensionsExportFileName => "DeepCloneableExtensions";

    /// <summary>
    /// The namespace for the generated extension methods.
    /// e.g. "IDeepCloneable.Generator"
    /// </summary>
    public virtual string ExtensionsNamespace => "IDeepCloneable.Generator";

    /// <summary>
    /// The class name for the generated extension methods.
    /// e.g. "DeepCloneableExtensions"
    /// </summary>
    public virtual string ExtensionsClassName => "DeepCloneableExtensions";

    /// <summary>
    /// The name of the DeepClone method to implement.
    /// e.g. "DeepClone"
    /// </summary>
    public virtual string ImplementsMethodName => "DeepClone";

    /// <summary>
    /// The metadata name of the attribute that marks properties/fields to be ignored during cloning.
    /// e.g. "CloneIgnoreAttribute"
    /// </summary>
    public virtual string CloneIgnoreAttributeName => "CloneIgnoreAttribute";

    /// <summary>
    /// The metadata name of the attribute that marks properties/fields to be shallow-copied during cloning.
    /// e.g. "ShallowCloneAttribute"
    /// </summary>
    public virtual string ShallowCloneAttributeName => "ShallowCloneAttribute";
}
