using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.CodeAnalysis;

namespace IDeepCloneable.Generator;

/// <summary>
/// Generates source code for deep cloning functionality.
/// </summary>
internal class CodeGenerator(CloneableGeneratorOptionsCore options)
{
    private static readonly List<SpecialTypeInfo> SpecialTypeInfos =
    [
        new ArrayTypeInfo(),
        new ListTypeInfo(),
        new DictionaryTypeInfo(),
        new HashSetTypeInfo(),
        new SortedSetTypeInfo(),
        new StackTypeInfo(),
        new QueueTypeInfo(),
        new ObservableCollectionTypeInfo(),
        new ReadOnlyCollectionTypeInfo(),
        new ImmutableListTypeInfo(),
        new ImmutableArrayTypeInfo(),
        new ImmutableHashSetTypeInfo(),
        new ImmutableDictionaryTypeInfo(),
        new IEnumerableTypeInfo(),
    ];

    /// <summary>
    /// Generates source code for deep cloning.
    ///
    /// NOTICE - Code Generation Rules:
    /// * All generated and referenced type names use fully qualified names starting with global:: to avoid name collisions.
    /// * Code generation uses IndentedStringBuilder for proper indentation.
    /// * Generated file headers follow a common format (see GenerateFileHeader).
    /// </summary>
    public void Execute(List<ClassInfo> classInfos, SourceProductionContext context)
    {
        if (classInfos.Count == 0)
            return;

        // Generate DeepCloneExtensions.g.cs
        var extensionsCode = GenerateDeepCloneExtensions(classInfos);
        context.AddSource($"{options.ExtensionsExportFileName}.g.cs", extensionsCode);

        // Generate partial class implementations for each type that needs DeepClone method
        // Skip types that already have DeepClone method defined (manual or from other generators)
        // Use full class name to avoid collisions when classes have the same simple name in different namespaces
        var generatedFiles = new HashSet<string>();
        foreach (
            var classInfo in classInfos.Where(c => c.NeedsDeepCloneMethod && !c.AlreadyHasDeepClone)
        )
        {
            var partialClassCode = GeneratePartialClass(classInfo);
            // Use sanitized full class name to ensure uniqueness
            var fileName =
                $"{CodeGenerationUtility.SanitizeTypeName(classInfo.FullClassName)}.{options.ImplementsMethodName}.g.cs";

            // Additional safety check to avoid duplicate file names
            if (!generatedFiles.Contains(fileName))
            {
                generatedFiles.Add(fileName);
                context.AddSource(fileName, partialClassCode);
            }
        }
    }

    private IndentedStringBuilder GenerateFileHeader(IndentedStringBuilder builder)
    {
        // File header format as specified in the original comments
        var header = $"""
            // <auto-generated>
            // {options.GeneratedHeaderComment}
            // </auto-generated>
            #nullable disable
            #pragma warning disable

            using System;
            using System.Collections.Generic;
            """;
        builder.AppendLine(header);
        return builder;
    }

    private string GenerateDeepCloneExtensions(List<ClassInfo> classInfos)
    {
        var builder = new IndentedStringBuilder();
        builder = GenerateFileHeader(builder);
        builder.AppendLine($"namespace {options.ExtensionsNamespace}");
        builder.AppendLine("{");
        builder.IncreaseIndent();
        builder.AppendLine(
            "[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]"
        );
        builder.AppendLine($"internal static partial class {options.ExtensionsClassName}");
        builder.AppendLine("{");
        builder.IncreaseIndent();

        // Generate CloneInternal methods for each class
        // Even if all properties are immutable, we still need to clone reference types (classes)
        // Only skip truly immutable types (value types with immutable fields, strings, etc.)
        // Also skip abstract classes (they can't be instantiated)
        // Also skip types that are handled by special type handlers
        foreach (var classInfo in classInfos)
        {
            // Check if this type is handled by a special type handler
            bool isSpecialType = false;
            foreach (var specialTypeInfo in SpecialTypeInfos)
            {
                if (specialTypeInfo.IsMatch(classInfo))
                {
                    isSpecialType = true;
                    break;
                }
            }

            // Skip only if it's a value type AND all properties are immutable
            // Or if it's an abstract class (can't instantiate)
            // Or if it's a special type (handled by special type handlers)
            var skipGeneration =
                classInfo.IsImmutableUsable || classInfo.IsAbstract || isSpecialType;

            if (!skipGeneration)
            {
                builder = GenerateCloneInternalMethod(classInfo, classInfos, builder);
            }
        }

        // Generate special collection clone methods
        builder = GenerateCollectionCloneMethods(classInfos, builder);

        builder.DecreaseIndent();
        builder.AppendLine("}");
        builder.DecreaseIndent();
        builder.AppendLine("}");

        return builder.ToString();
    }

    /// <summary>
    /// Determines whether to use 'with' syntax for cloning a record or value type.
    /// </summary>
    private bool ShouldUseWithSyntax(ClassInfo classInfo)
    {
        // Always use 'with' for reference type records to create a new instance
        // For value types, only use 'with' if there are mutable properties
        var hasNonImmutableProps = classInfo.Properties.Any(p => p.NeedsDeepClone);
        return hasNonImmutableProps || (classInfo.IsRecord && !classInfo.IsValueType);
    }

    private IndentedStringBuilder GenerateCloneInternalMethod(
        ClassInfo classInfo,
        List<ClassInfo> allClassInfos,
        IndentedStringBuilder builder
    )
    {
        var visibility = classInfo.NeedsDeepCloneMethod ? "internal" : "private";
        var methodName =
            CodeGenerationUtility.SanitizeTypeName(classInfo.FullClassName) + "_CloneInternal";
        var cacheFieldName = $"_cloneCache_{methodName}";

        // Include generic type parameters in method signature if present
        var genericParams = string.IsNullOrEmpty(classInfo.GenericTypeParameters)
            ? string.Empty
            : $"<{classInfo.GenericTypeParameters}>";

        builder.AppendLine("");

        // Method signature with optional clearCache parameter for circular reference handling
        if (classInfo.HasCircularReference)
        {
            // Add static cache field for circular reference handling - per type caching
            builder.AppendLine(
                $"""
                private static global::System.Collections.Concurrent.ConcurrentDictionary<int, {classInfo.FullClassName}> {cacheFieldName} = new();
                {CodeTemplateContents.EditorBrowsableAttribute}
                {visibility} static {classInfo.FullClassName} {methodName}{genericParams}(this {classInfo.FullClassName} original, bool clearCache = false)
                """
            );
        }
        else
        {
            builder.AppendLine($"{CodeTemplateContents.EditorBrowsableAttribute}");
            builder.AppendLine(
                $"{visibility} static {classInfo.FullClassName} {methodName}{genericParams}(this {classInfo.FullClassName} original)"
            );
        }

        builder.AppendLine("{");
        builder.IncreaseIndent();

        if (!classInfo.IsValueType)
        {
            builder.AppendLine("if (original == null) return null;");

            // For circular references, use static cache field
            if (classInfo.HasCircularReference)
            {
                builder = GenerateCircularReferenceCheck(classInfo, cacheFieldName, builder);
            }
        }

        if (classInfo.IsRecord || classInfo.IsValueType)
        {
            builder = GenerateRecordOrValueTypeClone(classInfo, allClassInfos, builder);
        }
        else
        {
            builder = GenerateClassClone(classInfo, allClassInfos, cacheFieldName, builder);
        }

        builder.DecreaseIndent();
        builder.AppendLine("}");

        return builder;
    }

    /// <summary>
    /// Generates circular reference checking logic using static per-type cache.
    /// </summary>
    private IndentedStringBuilder GenerateCircularReferenceCheck(
        ClassInfo classInfo,
        string cacheFieldName,
        IndentedStringBuilder builder
    )
    {
        builder.AppendLine(
            $$"""
            if (clearCache || {{cacheFieldName}} == null)
            {
                {{cacheFieldName}} = new();
            }
            var hashCode = original.GetHashCode();
            if ({{cacheFieldName}}.TryGetValue(hashCode, out var cached))
            {
                return cached;
            }
            """
        );
        return builder;
    }

    /// <summary>
    /// Generates clone logic for records and value types using 'with' syntax.
    /// </summary>
    private IndentedStringBuilder GenerateRecordOrValueTypeClone(
        ClassInfo classInfo,
        List<ClassInfo> allClassInfos,
        IndentedStringBuilder builder
    )
    {
        if (ShouldUseWithSyntax(classInfo))
        {
            builder.AppendLine("return original with");
            builder.AppendLine("{");
            builder.IncreaseIndent();

            foreach (var prop in classInfo.Properties)
            {
                // For properties marked with [CloneIgnore], explicitly set to default
                if (prop.IsCloneIgnored)
                {
                    builder.AppendLine($"{prop.Name} = default,");
                }
                // For [ShallowClone], just copy the reference
                else if (prop.IsShallowClone)
                {
                    builder.AppendLine($"{prop.Name} = original.{prop.Name},");
                }
                else if (prop.NeedsDeepClone)
                {
                    var cloneCall = GeneratePropertyCloneCall(prop, allClassInfos);
                    builder.AppendLine($"{prop.Name} = {cloneCall},");
                }
            }

            builder.DecreaseIndent();
            builder.AppendLine("};");
        }
        else
        {
            // Only return original for immutable value types
            builder.AppendLine("return original;");
        }
        return builder;
    }

    /// <summary>
    /// Generates clone logic for classes (non-record reference types).
    /// Handles required properties, copy constructors, and circular references.
    /// </summary>
    private IndentedStringBuilder GenerateClassClone(
        ClassInfo classInfo,
        List<ClassInfo> allClassInfos,
        string cacheFieldName,
        IndentedStringBuilder builder
    )
    {
        // Check for required properties
        var requiredProps = classInfo.Properties.Where(p => p.IsRequired).ToList();
        var nonRequiredProps = classInfo.Properties.Where(p => !p.IsRequired).ToList();

        // Determine how to create the instance
        if (classInfo.HasCopyConstructor)
        {
            builder = GenerateCopyConstructorClone(
                classInfo,
                allClassInfos,
                cacheFieldName,
                builder
            );
        }
        else if (requiredProps.Any())
        {
            builder = GenerateRequiredPropertiesClone(
                classInfo,
                requiredProps,
                nonRequiredProps,
                allClassInfos,
                cacheFieldName,
                builder
            );
        }
        else
        {
            builder = GenerateDefaultConstructorClone(
                classInfo,
                allClassInfos,
                cacheFieldName,
                builder
            );
        }
        builder.AppendLine("return clone;");
        return builder;
    }

    /// <summary>
    /// Generates clone logic using copy constructor.
    /// </summary>
    private IndentedStringBuilder GenerateCopyConstructorClone(
        ClassInfo classInfo,
        List<ClassInfo> allClassInfos,
        string cacheFieldName,
        IndentedStringBuilder builder
    )
    {
        // Use copy constructor
        builder.AppendLine($"var clone = new {classInfo.FullClassName}(original);");
        if (classInfo.HasCircularReference)
        {
            builder.AppendLine($"{cacheFieldName}[hashCode] = clone;");
        }

        // Override properties with deep clones or handle special attributes
        foreach (var prop in classInfo.Properties)
        {
            // Skip properties marked with [CloneIgnore] - they keep default/copied value
            if (prop.IsCloneIgnored)
            {
                // Set to default value to ignore the copy constructor's value
                builder.AppendLine($"clone.{prop.Name} = default;");
            }
            // For [ShallowClone], just copy the reference (already done by copy constructor)
            else if (prop.IsShallowClone)
            {
                // No action needed - copy constructor already copied the reference
            }
            else if (!prop.IsImmutable)
            {
                var cloneCall = GeneratePropertyCloneCall(prop, allClassInfos);
                builder.AppendLine($"clone.{prop.Name} = {cloneCall};");
            }
        }
        return builder;
    }

    /// <summary>
    /// Generates clone logic for classes with required properties using object initializer.
    /// </summary>
    private IndentedStringBuilder GenerateRequiredPropertiesClone(
        ClassInfo classInfo,
        List<PropertyInfo> requiredProps,
        List<PropertyInfo> nonRequiredProps,
        List<ClassInfo> allClassInfos,
        string cacheFieldName,
        IndentedStringBuilder builder
    )
    {
        // Use object initializer for required properties
        builder.AppendLine($"var clone = new {classInfo.FullClassName}");
        builder.AppendLine("{");
        builder.IncreaseIndent();

        foreach (var prop in requiredProps)
        {
            // Skip properties marked with [CloneIgnore] - they keep default value
            if (prop.IsCloneIgnored)
            {
                // Required properties can't be skipped in initializer, set to default
                builder.AppendLine($"{prop.Name} = default,");
            }
            else
            {
                var cloneCall = GeneratePropertyCloneCall(prop, allClassInfos);
                builder.AppendLine($"{prop.Name} = {cloneCall},");
            }
        }

        builder.DecreaseIndent();
        builder.AppendLine("};");

        if (classInfo.HasCircularReference)
        {
            builder.AppendLine($"{cacheFieldName}[hashCode] = clone;");
        }

        // Set non-required properties
        foreach (var prop in nonRequiredProps)
        {
            // Skip properties marked with [CloneIgnore]
            if (prop.IsCloneIgnored)
                continue;

            // For [ShallowClone], just copy the reference
            if (prop.IsShallowClone)
            {
                builder.AppendLine($"clone.{prop.Name} = original.{prop.Name};");
            }
            else if (prop.IsImmutable)
            {
                builder.AppendLine($"clone.{prop.Name} = original.{prop.Name};");
            }
            else
            {
                var cloneCall = GeneratePropertyCloneCall(prop, allClassInfos);
                builder.AppendLine($"clone.{prop.Name} = {cloneCall};");
            }
        }
        return builder;
    }

    /// <summary>
    /// Generates clone logic for classes using default parameterless constructor.
    /// </summary>
    private IndentedStringBuilder GenerateDefaultConstructorClone(
        ClassInfo classInfo,
        List<ClassInfo> allClassInfos,
        string cacheFieldName,
        IndentedStringBuilder builder
    )
    {
        builder.AppendLine($"var clone = new {classInfo.FullClassName}();");
        if (classInfo.HasCircularReference)
        {
            builder.AppendLine($"{cacheFieldName}[hashCode] = clone;");
        }

        foreach (var prop in classInfo.Properties)
        {
            // Skip properties marked with [CloneIgnore]
            if (prop.IsCloneIgnored)
                continue;

            // For [ShallowClone], just copy the reference
            if (prop.IsShallowClone)
            {
                builder.AppendLine($"clone.{prop.Name} = original.{prop.Name};");
            }
            else if (prop.IsImmutable)
            {
                builder.AppendLine($"clone.{prop.Name} = original.{prop.Name};");
            }
            else
            {
                var cloneCall = GeneratePropertyCloneCall(prop, allClassInfos);
                builder.AppendLine($"clone.{prop.Name} = {cloneCall};");
            }
        }
        return builder;
    }

    private string GeneratePropertyCloneCall(PropertyInfo prop, List<ClassInfo> allClassInfos)
    {
        var propertyAccess = $"original.{prop.Name}";

        // For nullable properties
        if (prop.IsNullable)
        {
            // If it's a nullable value type (immutable), we can just assign directly
            // e.g., DateTime? can be assigned without null check: clone.UpdateAt = original.UpdateAt
            if (prop.IsImmutable)
            {
                return propertyAccess;
            }
            // For nullable reference types, we need the null check to avoid calling clone on null
            else
            {
                var cloneCall = GenerateTypeCloneCall(
                    prop.TypeFullName,
                    propertyAccess,
                    allClassInfos
                );
                // For type parameters, use default(T) instead of null
                // Type parameters don't need global:: prefix
                var typeForDefault = prop.TypeFullName.Replace("global::", "");
                var nullValue = CodeGenerationUtility.IsSimpleTypeParameter(prop.TypeFullName) 
                    ? $"default({typeForDefault})" 
                    : "null";
                return $"{propertyAccess} != null ? {cloneCall} : {nullValue}";
            }
        }
        else
        {
            return GenerateTypeCloneCall(prop.TypeFullName, propertyAccess, allClassInfos);
        }
    }

    /// <summary>
    /// Generates a clone call for a specific type.
    /// No longer needs cache parameter as it's now a static field.
    /// </summary>
    public string GenerateTypeCloneCall(
        string typeFullName,
        string valueExpression,
        List<ClassInfo> allClassInfos
    )
    {
        if (CodeGenerationUtility.IsTypeImmutable(typeFullName))
        {
            return valueExpression;
        }
        
        // For type parameters, use shallow copy (assign directly)
        // We can't deep clone unconstrained type parameters without adding constraints
        // which would require constraint propagation throughout the call chain
        if (CodeGenerationUtility.IsSimpleTypeParameter(typeFullName))
        {
            return valueExpression;
        }

        // Check special types using SpecialTypeInfo (includes arrays)
        foreach (var specialTypeInfo in SpecialTypeInfos)
        {
            if (specialTypeInfo.IsMatch(typeFullName))
            {
                var methodName = specialTypeInfo.GetMethodName(typeFullName);
                return $"{methodName}({valueExpression})";
            }
        }

        // Regular type - need to find the matching ClassInfo to get the correct generic parameters
        // For generic types, we need to use the method based on the generic definition, not the concrete type
        // e.g., CustomEnumerable<string> should call CustomEnumerable_T__CloneInternal<string>
        
        // First, try to find a matching ClassInfo
        var matchingClassInfo = FindMatchingGenericClassInfo(typeFullName, allClassInfos);
        
        string sanitizedName;
        List<string> genericArgs;
        
        if (matchingClassInfo != null)
        {
            // Use the generic definition's full name for the method name
            sanitizedName = CodeGenerationUtility.SanitizeTypeName(matchingClassInfo.FullClassName);
            // Use the actual type's arguments for the call
            genericArgs = ExtractGenericTypeArguments(typeFullName);
        }
        else
        {
            // Fall back to the original behavior for non-generic or unknown types
            sanitizedName = CodeGenerationUtility.SanitizeTypeName(typeFullName);
            genericArgs = ExtractGenericTypeArguments(typeFullName);
        }
        
        var genericArgsStr = genericArgs.Count > 0 ? $"<{string.Join(", ", genericArgs)}>" : string.Empty;
        
        return $"{sanitizedName}_CloneInternal{genericArgsStr}({valueExpression})";
    }
    
    /// <summary>
    /// Finds a matching ClassInfo for a potentially concrete generic type.
    /// E.g., for "CustomEnumerable<string>", finds the ClassInfo for "CustomEnumerable<T>"
    /// </summary>
    private ClassInfo? FindMatchingGenericClassInfo(string typeFullName, List<ClassInfo> allClassInfos)
    {
        // Extract the base type name without generic arguments
        var baseTypeName = ExtractBaseTypeName(typeFullName);
        
        foreach (var classInfo in allClassInfos)
        {
            var classBaseTypeName = ExtractBaseTypeName(classInfo.FullClassName);
            if (baseTypeName == classBaseTypeName && !string.IsNullOrEmpty(classInfo.GenericTypeParameters))
            {
                return classInfo;
            }
        }
        
        return null;
    }
    
    /// <summary>
    /// Extracts the base type name without generic arguments.
    /// E.g., "global::MyNamespace.MyClass<string, int>" -> "global::MyNamespace.MyClass"
    /// </summary>
    private string ExtractBaseTypeName(string typeFullName)
    {
        var genericStart = typeFullName.IndexOf('<');
        if (genericStart < 0)
            return typeFullName;
        return typeFullName.Substring(0, genericStart);
    }
    
    /// <summary>
    /// Extracts generic type arguments from a type name (e.g., "string" from "MyClass<string>")
    /// </summary>
    private List<string> ExtractGenericTypeArguments(string typeFullName)
    {
        var result = new List<string>();
        var startIndex = typeFullName.IndexOf('<');
        if (startIndex < 0)
            return result;
            
        var endIndex = typeFullName.LastIndexOf('>');
        if (endIndex <= startIndex)
            return result;
            
        var typeArgsString = typeFullName.Substring(startIndex + 1, endIndex - startIndex - 1);
        var typeArgs = CodeGenerationUtility.SplitGenericArgs(typeArgsString);
        
        foreach (var typeArg in typeArgs)
        {
            result.Add(typeArg.Trim());
        }
        
        return result;
    }

    private IndentedStringBuilder GenerateCollectionCloneMethods(
        List<ClassInfo> classInfos,
        IndentedStringBuilder builder
    )
    {
        var generatedMethods = new HashSet<string>();
        var typesToProcess = new Queue<string>();

        // First, collect all property types
        foreach (var classInfo in classInfos)
        {
            foreach (var prop in classInfo.Properties)
            {
                typesToProcess.Enqueue(prop.TypeFullName);
            }
        }

        // Process types and their nested types
        while (typesToProcess.Count > 0)
        {
            var typeFullName = typesToProcess.Dequeue();

            // Check special types using SpecialTypeInfo (now includes arrays)
            foreach (var specialTypeInfo in SpecialTypeInfos)
            {
                if (specialTypeInfo.IsMatch(typeFullName))
                {
                    var methodName = specialTypeInfo.GetMethodName(typeFullName);

                    if (!generatedMethods.Contains(methodName))
                    {
                        generatedMethods.Add(methodName);
                        builder = specialTypeInfo.GenerateCloneMethod(
                            typeFullName,
                            methodName,
                            classInfos,
                            builder,
                            this
                        );

                        // Extract inner type(s) and add to queue for processing
                        var innerType = CodeGenerationUtility.ExtractGenericType(typeFullName);
                        if (innerType != typeFullName && !string.IsNullOrEmpty(innerType))
                        {
                            typesToProcess.Enqueue(innerType);
                        }

                        // For arrays, also extract and queue the element type
                        if (typeFullName.Contains("[") && typeFullName.Contains("]"))
                        {
                            var bracketIndex = typeFullName.IndexOf('[');
                            var elementType = typeFullName.Substring(0, bracketIndex);
                            if (!string.IsNullOrEmpty(elementType))
                            {
                                typesToProcess.Enqueue(elementType);
                            }
                        }
                    }
                    break;
                }
            }
        }

        return builder;
    }

    private string GeneratePartialClass(ClassInfo classInfo)
    {
        var builder = new IndentedStringBuilder();
        builder = GenerateFileHeader(builder);

        // Generate namespace if present
        if (!string.IsNullOrEmpty(classInfo.Namespace))
        {
            builder.AppendLine($"namespace {classInfo.Namespace}");
            builder.AppendLine("{");
            builder.IncreaseIndent();
        }

        // Generate containing type declarations for nested classes
        foreach (var containingTypeName in classInfo.ContainingTypeNames)
        {
            builder.AppendLine($"partial class {containingTypeName}");
            builder.AppendLine("{");
            builder.IncreaseIndent();
        }

        var typeKeyword = classInfo.IsRecord
            ? (classInfo.IsValueType ? "record struct" : "record")
            : (classInfo.IsValueType ? "struct" : "class");

        // Include generic type parameters in partial class declaration if present
        var genericParams = string.IsNullOrEmpty(classInfo.GenericTypeParameters)
            ? string.Empty
            : $"<{classInfo.GenericTypeParameters}>";

        var implementInterface = !string.IsNullOrWhiteSpace(options.ImplementedInterfaceName)
            ? $" : {options.ImplementedInterfaceName}<{classInfo.FullClassName}>"
            : string.Empty;
        builder.AppendLine($"partial {typeKeyword} {classInfo.ClassName}{genericParams}{implementInterface}");
        builder.AppendLine("{");
        builder.IncreaseIndent();
        builder.AppendLine("/// <inheritdoc />");

        var modifiers = "public";
        if (!classInfo.IsSealed && !classInfo.IsValueType)
        {
            if (classInfo.IsAbstract)
                modifiers += " abstract";
            else if (classInfo.BaseHasDeepClone)
                modifiers += " override";
            else
                modifiers += " virtual";
        }

        var sanitizedName = CodeGenerationUtility.SanitizeTypeName(classInfo.FullClassName);

        if (classInfo.IsAbstract)
        {
            // Abstract classes have abstract DeepClone method without implementation
            builder.AppendLine(
                $"{modifiers} {classInfo.FullClassName} {options.ImplementsMethodName}();"
            );
        }
        else if (classInfo.IsImmutableUsable)
        {
            // Immutable value types can just return themselves
            builder.AppendLine(
                $"{modifiers} {classInfo.FullClassName} {options.ImplementsMethodName}()"
            );
            builder.AppendLine("    => this;");
        }
        else if (classInfo.HasCircularReference)
        {
            builder.AppendLine(
                $"{modifiers} {classInfo.FullClassName} {options.ImplementsMethodName}()"
            );
            builder.AppendLine(
                $"    => global::{options.ExtensionsNamespace}.{options.ExtensionsClassName}.{sanitizedName}_CloneInternal(this, clearCache: true);"
            );
        }
        else
        {
            // No circular references in entire codebase, use simple expression body
            builder.AppendLine(
                $"{modifiers} {classInfo.FullClassName} {options.ImplementsMethodName}()"
            );
            builder.AppendLine(
                $"    => global::{options.ExtensionsNamespace}.{options.ExtensionsClassName}.{sanitizedName}_CloneInternal(this);"
            );
        }

        builder.DecreaseIndent();
        builder.AppendLine("}");

        // Close containing type declarations
        for (int i = 0; i < classInfo.ContainingTypeNames.Count; i++)
        {
            builder.DecreaseIndent();
            builder.AppendLine("}");
        }

        // Close namespace if present
        if (!string.IsNullOrEmpty(classInfo.Namespace))
        {
            builder.DecreaseIndent();
            builder.AppendLine("}");
        }

        return builder.ToString();
    }
}
