<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>IDeepCloneable.Generator</RootNamespace>
    <ImplicitUsings>disable</ImplicitUsings>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <NuSpecFile>GeneratorSource.nuspec</NuSpecFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="lint4sg" Version="0.1.6" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.4.0" />
    <PackageReference Include="Polyfill" Version="10.3.0" Condition="!Exists('packages.config')">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <Target Name="SetPackageDependencies" BeforeTargets="GenerateNuspec">
    <PropertyGroup>
      <NuspecProperties>configuration=$(Configuration);version=$(PackageVersion);authors=$(Authors);projectUrl=$(PackageProjectUrl);description=$(PackageDescription)</NuspecProperties>
    </PropertyGroup>
  </Target>
</Project>
