<Project>
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <IsPackable>true</IsPackable>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <PackageDescription>Automatic implementation generator for the IDeepCloneable interface via source generators.</PackageDescription>
    <PackageProjectUrl>https://github.com/arika0093/IDeepCloneable</PackageProjectUrl>
    <RepositoryUrl>https://github.com/arika0093/IDeepCloneable</RepositoryUrl>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <Authors>arika0093</Authors>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference
      Include="Nerdbank.GitVersioning"
      Version="3.*"
      Condition="!Exists('packages.config')"
    >
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
