name: Run Benchmarks

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5

      - name: Restore dependencies
        run: dotnet restore

      - name: Run benchmarks
        run: dotnet run --project benchmark/IDeepCloneable.Benchmark/IDeepCloneable.Benchmark.csproj -c Release

      - name: Move Benchmark Result
        run: mv BenchmarkDotNet.Artifacts/results/IDeepCloneable.Benchmark.CloneBenchmarks-report-github.md benchmark/BenchmarkResults.md

      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "[skip-ci] chore: update benchmark summary"
