name: Run Simple Benchmark

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**.csproj'
      - '**.cs'
      - '**./Directories.Build.props'
      - '.github/workflows/format.yaml'
        
permissions:
  contents: write

jobs:
  simple-benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v6

      - name: Restore dependencies
        run: dotnet restore

      - name: Run benchmarks only IDeepCloneable
        run: dotnet run --project benchmark/IDeepCloneable.Benchmark/IDeepCloneable.Benchmark.csproj -c Release -- --filter IDeepCloneable.Benchmark.CloneBenchmarks.IDeepCloneable

      - name: Move Benchmark Result
        shell: bash
        run: mv -f BenchmarkDotNet.Artifacts/results/IDeepCloneable.Benchmark.CloneBenchmarks-report-github.md benchmark/results/performance-check.md

      - name: Pull before commit
        run: git pull origin ${{ github.ref_name }}

      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "[skip-ci] chore: update benchmark summary"
          branch: ${{ github.ref_name }}
